add_newline = false

[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"
vimcmd_symbol = "[](bold green)"
vimcmd_replace_one_symbol = "[](bold purple)"
vimcmd_replace_symbol = "[](bold purple)"
vimcmd_visual_symbol = "[](bold yellow)"

[line_break]
disabled = true

[git_status]
conflicted = "!"
ahead = "↑"
behind = "↓"
diverged = "↕"
untracked = "?"
stashed = "" # Here we use the nerd font icon to prevent an error
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[git_branch]
symbol = "שׂ "

[cmd_duration]
format = "[$duration]($style) "

[hostname]
format = "[$hostname]($style) "

[username]
disabled = true




# Disable all language specific modules

[bun]
disabled = true

[buf]
disabled = true

[cmake]
disabled = true

[cobol]
disabled = true

[crystal]
disabled = true

[daml]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[golang]
disabled = true

[haxe]
disabled = true

[helm]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[lua]
disabled = true

[meson]
disabled = true

[nim]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[opa]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[raku]
disabled = true

[red]
disabled = true

[rlang]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[swift]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[zig]
disabled = true
