add_newline = false
format = """
$hostname\
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$cmd_duration\
$jobs\
$battery\
$status\
$container\
$shell\
$character
"""

[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"
vimcmd_symbol = "[](bold green)"
vimcmd_replace_one_symbol = "[](bold purple)"
vimcmd_replace_symbol = "[](bold purple)"
vimcmd_visual_symbol = "[](bold yellow)"

[line_break]
disabled = true

[git_status]
conflicted = "!"
ahead = "↑"
behind = "↓"
diverged = "↕"
untracked = "?"
stashed = "" # Here we use the nerd font icon to prevent an error
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[cmd_duration]
format = "[$duration]($style) "

[hostname]
format = "[$hostname]($style) "

[username]
format = "[~$user]($style) "

[container]
format = "i'm in a box"
