add_newline = false

[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"
vimcmd_symbol = "[](bold green)"
vimcmd_replace_one_symbol = "[](bold purple)"
vimcmd_replace_symbol = "[](bold purple)"
vimcmd_visual_symbol = "[](bold yellow)"

[line_break]
disabled = true

[git_status]
conflicted = "!"
ahead = "↑"
behind = "↓"
diverged = "↕"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[git_branch]
symbol = "שׂ "

[cmd_duration]
format = "[$duration]($style) "
